### ISSUE TITLE
Error: ENOENT: no such file or directory, stat ''

### ISSUE THREAD

**Issue by Sturgelose** [nscaife/linter-chktex#19]
I get this error every time that the module is used:

```
Error: ENOENT: no such file or directory, stat ''
    at Error (native)
    at fs.statSync (fs.js:854:18)
    at Object.fs.statSync (ATOM_SHELL_ASAR.js:225:16)
    at /home/sturgelose/.atom/packages/linter-chktex/lib/linter-chktex.coffee:43:24
    at Object.provider.lint (/home/sturgelose/.atom/packages/linter-chktex/lib/linter-chktex.coffee:38:20)
    at promises.push.Promise.then._this.emitter.emit.linter (/home/sturgelose/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /home/sturgelose/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/home/sturgelose/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /home/sturgelose/.atom/packages/linter/lib/linter.coffee:88:16
```

It seems something related to the name of a file or folder... Any idea on how to fix this?

**Comment by nscaife** [comment]
This should be fixed in the latest release!
