### ISSUE TITLE
ChkTeX does not handle lines over 1024 bytes correctly. 

### ISSUE THREAD

**Issue by kingwyf87** [nscaife/linter-chktex#41]
Tried to use chktex in atom (linter v2.2.0; linter-chktex v1.3.1) on MacOS, and got the below errors:

/Users/yifei-macpro/.atom/packages/linter/lib/linter-registry.js:159 [Linter] Error running chktex Error: chktex: WARNING -- ChkTeX does not handle lines over 1024 bytes correctly.  Some errors and line numbers may be wrong in this file.
chktex: WARNING -- ChkTeX could not fully expand tabs because the resulting line would be more than 1024 bytes.  Some errors and line numbers may be wrong in this file.

    at exit (/Users/yifei-macpro/.atom/packages/linter-chktex/node_modules/atom-linter/lib/helpers.js:58:20)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:351:17
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

**Comment by nscaife** [comment]
This is a problem with chktex, which cannot handle lines over 1024 bytes.

**Comment by kingwyf87** [comment]
@nscaife But why chktex is working fine on SublimeLinter-chktex? How to check chktex?
